# Generated by Django 5.0 on 2023-12-10 19:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('share_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sender_id', models.CharField(max_length=255, verbose_name='sender id')),
                ('recipient_id', models.CharField(max_length=255, verbose_name='recipient id')),
                ('file_id', models.CharField(max_length=255, verbose_name='file id')),
                ('share_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='share timestamp')),
            ],
            options={
                'verbose_name': 'Share',
                'verbose_name_plural': 'Shares',
            },
        ),
    ]
