# Generated by Django 5.0 on 2023-12-10 07:29

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.CharField(max_length=255, verbose_name='user id')),
                ('size', models.FloatField(verbose_name='size')),
                ('file_name', models.CharField(max_length=255, verbose_name='file name')),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2023, 12, 10, 7, 29, 46, 505662, tzinfo=datetime.timezone.utc), verbose_name='Upload Date')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
