# Generated by Django 5.0 on 2023-12-10 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload Date'),
        ),
    ]
