# Generated by Django 5.0 on 2023-12-10 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_file_id_alter_file_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='upload_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
