# Generated by Django 5.0 on 2023-12-09 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(default='user', max_length=255, verbose_name='user name')),
                ('email', models.EmailField(max_length=254, verbose_name='user email')),
                ('phone', models.CharField(default=None, max_length=10, null=True, verbose_name='phone number')),
                ('password', models.CharField(default=None, max_length=255, null=True, verbose_name='password')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
